import type { Metadata } from "next";
import "./globals.css";
import Providers from "@/contents/ProgressProvider";
import { Toaster } from "@/components/ui/sonner";

export const metadata: Metadata = {
  title: "Chamber Queue Management",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`min-h-screen antialiased`}>
        <Providers>
          {children}
          <Toaster position="top-right" closeButton richColors />
        </Providers>
      </body>
    </html>
  );
}
